version: '3'
services:
  
  postgres:
    image: postgis/postgis
    container_name: dbt-postgres
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/sql/init-db.sh:/docker-entrypoint-initdb.d/init-table-db.sh

volumes:
  postgresql_data:

