
version: 2

sources:
  - name: maelys
    database: postgres
    schema: public

    tables:
      - name: transactions


models:
  - name: refund_retrocharge
    description: "refund_retrocharge table"
    columns:
      - name: order_id
        description: "order"
        tests:
          - not_null
      - name: payment_id
        tests:
          - not_null
          - relationships:
              to: ref('single_pay')
              field: pay_id
          - relationships:
              to: ref('transaction_meta')
              field: id
      - name: marketplace_id
        tests:
          - not_null
          - relationships:
              to: ref('marketplace')
              field: id

  - name: chargeback_refund
    description: "chargeback_refund relation"
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('transaction_meta')
              field: id
      - name: payment_id
        tests:
          - not_null
          - relationships:
              to: ref('single_pay')
              field: pay_id 
      - name: marketplace_id
        tests:
          - not_null
          - relationships:
              to: ref('marketplace')
              field: id
      - name: city_id
        tests:
          - not_null
          - relationships:
              to: ref('city')
              field: id
      - name: sku_id
        tests:
          - not_null
          - relationships:
              to: ref('sku')
              field: id

  