
version: 2

sources:
  - name: maelys
    database: postgres
    schema: public

    tables:
      - name: transactions


models:
  - name: refund_retrocharge
    description: "refund_retrocharge table"
    columns:
      - name: order_id
        description: "order"
        tests:
          - not_null

  - name: marketplace
    description: "marketplace"
    columns:
      - name: marketplace_id
        description: "id of the marketplace"
        tests:
          - not_null
      - name: name
        tests:
          - not_null


