
version: 2

sources:
  - name: maelys
    database: postgres
    schema: public

    tables:
      - name: transactions


models:
  - name: refund_retrocharge
    description: "refund_retrocharge table"
    columns:
      - name: order_id
        description: "order"
        tests:
          - not_null
      - name: payment_id
        tests:
          - not_null
          - relationships:
              to: ref('single_pay')
              field: pay_id
          - relationships:
              to: ref('transaction_meta')
              field: id
      - name: marketplace_id
        tests:
          - not_null
          - relationships:
              to: ref('marketplace')
              field: id

  - name: chargeback_refund
    description: "chargeback_refund relation"
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('transaction_meta')
              field: id
      - name: payment_id
        tests:
          - not_null
          - relationships:
              to: ref('single_pay')
              field: pay_id 
      - name: marketplace_id
        tests:
          - not_null
          - relationships:
              to: ref('marketplace')
              field: id
      - name: city_id
        tests:
          - not_null
          - relationships:
              to: ref('city')
              field: id
      - name: sku_id
        tests:
          - not_null
          - relationships:
              to: ref('sku')
              field: id

  - name: adjustment
    description: "Adjustment relation"
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('transaction_meta')
              field: id
      - name: payment_id
        tests:
          - not_null
          - relationships:
              to: ref('single_pay')
              field: pay_id 
      - name: sku_id
        tests:
          - not_null
          - relationships:
              to: ref('sku')
              field: id
      - name: order_id
        tests:
          - not_null

  - name: transfer
    description: "Transfer relation"
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('transaction_meta')
              field: id
      - name: payment_id
        tests:
          - not_null
          - relationships:
              to: ref('single_pay')
              field: pay_id 

  - name: service_fee
    description: "Service Fee relation"
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('transaction_meta')
              field: id
      - name: payment_id
        tests:
          - not_null
          - relationships:
              to: ref('single_pay')
              field: pay_id 
      - name: marketplace_id
        tests:
          - not_null
          - relationships:
              to: ref('marketplace')
              field: id

  - name: fba_inventory_fee
    description: "FBA Inventory Fee relation"
    columns:
      - name: id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('transaction_meta')
              field: id
      - name: payment_id
        tests:
          - not_null
          - relationships:
              to: ref('single_pay')
              field: pay_id 
      - name: marketplace_id
        tests:
          - not_null
          - relationships:
              to: ref('marketplace')
              field: id
  