
version: 2

sources:
  - name: maelys
    database: postgres
    schema: public

    tables:
      - name: parsed_data_types


models:
  - name: refund_retrocharge
    description: "refund_retrocharge table"
    columns:
      - name: order_id
        description: "order"
        # That is the question
        tests:
          - unique
          - not_null

  - name: marketplace
    description: "marketplace"
    columns:
      - name: id
        description: "marketplace id"
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - unique
          - not_null


