
version: 2

sources:
  - name: maelys
    database: postgres
    schema: public

    tables:
      - name: parsed_data_types


models:
  - name: transactions
    description: "clean fact table with data types"
    columns:
      - name: id
        type: bigserial
        description: "id of fact"
        tests:
          - unique
          - not_null

  - name: marketplace
    description: "marketplace"
    columns:
      - name: id
        description: "id of the marketplace"
        tests:
          - not_null
      - name: name
        tests:
          - not_null

  - name: payment_total
    description: "total view"
    columns:
      - name: pay_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('single_pay')
              field: pay_id
      - name: total
        description: "sum of payments, include any type of payment"
        tests:
          - not_null

  - name: single_pay
    description: "single_pay model"
    columns:
      - name: pay_id
        tests:
          - not_null
      - name: pay_type
        type: pay_type
        description: "enumeration of payment types"
        tests:
          - not_null
          - accepted_values:
              values: [
                'product_sales', 'product_sales_tax', 
                'shipping_credits', 'shipping_credits_tax', 
                'gift_wrap_credits', 'giftwrap_credits_tax', 
                'regulatory_fee', 'tax_on_regulatory_fee', 
                'promotional_rebates', 'promotional_rebates_tax', 
                'marketplace_withheld_tax', 'selling_fees', 
                'fba_fees', 'other_transaction_fees', 'other'
              ]
      - name: amount
        description: "amount of payment type"
        tests:
          - not_null

  - name: city
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: order_city
        tests:
          - not_null
      - name: order_state
        tests:
          - not_null
      - name: order_postal
        tests:
          - not_null
